name: Build and Push Prizetown API Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: christianrobertson36
  API_IMAGE: prizetown-api
  API_TAG: v24

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: |
          docker build -t $REGISTRY/$OWNER/$API_IMAGE:$API_TAG ./api

      - name: Push API image
        run: |
          docker push $REGISTRY/$OWNER/$API_IMAGE:$API_TAG
