name: Build and Push Prizetown Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: christianrobertson36
  API_IMAGE: prizetown-api
  API_TAG: v252
  WEB_IMAGE: prizetown-web
  WEB_TAG: v252
  VITE_API_URL: https://api.prizetown.co.uk

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: docker build -t $REGISTRY/$OWNER/$API_IMAGE:$API_TAG ./api

      - name: Push API image
        run: docker push $REGISTRY/$OWNER/$API_IMAGE:$API_TAG

  build-web:
    runs-on: ubuntu-latest
    needs: build-api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build web image
        run: |
          docker build \
            --build-arg VITE_API_URL=$VITE_API_URL \
            -t $REGISTRY/$OWNER/$WEB_IMAGE:$WEB_TAG \
            ./web

      - name: Push web image
        run: docker push $REGISTRY/$OWNER/$WEB_IMAGE:$WEB_TAG




